---
title: "RH work"
output: pdf_document
date: "2026-01-26"
---

```{r}
rm(list = ls())
setwd("/cloud/project/data")
# renv::activate()
library(terra)
library(rts)
library(maps)
library(EWSmethods)
```

```{r}
Td <- terra::rast("data/dew_point_2001-2025.nc")
T <-terra::rast("data/ERA5_tas_2001-2023.nc")

# Let's subset Jan 2001 to Dec 2015
data <- terra::subset(Td, 1:180)
# Let's focus on Canada
data1 <- crop(x=data, y = c(219.0, 307.4, 41.7, 83.1))
             
# Let's subset Jan 2001 to Dec 2015
data <- terra::subset(T, 1:180)
# Let's focus on Canada
data2 <- crop(x=data, y = c(219.0, 307.4, 41.7, 83.1))

e_data2 <- 6.112 * exp ((17.67 * data2)/(data2 + 243.5))
e_data1 <- 6.112 * exp ((17.67 * data1)/(data1 + 243.5))

RH <- (e_data1 / e_data2) * 100

terra::writeCDF(x = RH, filename = "data/relativeHumidity.nc", varname = "RH", longname = "Relative Humidity (%)", overwrite = TRUE)

```
# Northern Hemisphere RH c(0, 360, 0, 90) 
```{r}
Td <- terra::rast("data/dew_point_2001-2025.nc")
T <-terra::rast("data/ERA5_tas_2001-2023.nc")

# Let's subset Jan 2001 to Dec 2015
data <- terra::subset(Td, 1:180)
# Let's focus on Canada
data1 <- crop(x=data, y = c(0, 360, 0, 90) )
             
# Let's subset Jan 2001 to Dec 2015
data <- terra::subset(T, 1:180)
# Let's focus on Canada
data2 <- crop(x=data, y = c(0, 360, 0, 90) )

e_data2 <- 6.112 * exp ((17.67 * data2)/(data2 + 243.5))
e_data1 <- 6.112 * exp ((17.67 * data1)/(data1 + 243.5))

RH <- (e_data1 / e_data2) * 100

terra::writeCDF(x = RH, filename = "data/NHrelativeHumidity.nc", varname = "RH", longname = "Relative Humidity (%)", overwrite = TRUE)

```

# global RH (wont run)
```{r}
Td <- terra::rast("data/dew_point_2001-2025.nc")
T <-terra::rast("data/ERA5_tas_2001-2023.nc")

# Let's subset Jan 2001 to Dec 2015
data1 <- terra::subset(Td, 1:180)
# Let's focus on Canada

             
# Let's subset Jan 2001 to Dec 2015
data2 <- terra::subset(T, 1:180)
# Let's focus on Canada

e_data2 <- 6.112 * exp ((17.67 * data2)/(data2 + 243.5))
e_data1 <- 6.112 * exp ((17.67 * data1)/(data1 + 243.5))

RH <- (e_data1 / e_data2) * 100

terra::writeCDF(x = RH, filename = "data/globalrelativeHumidity.nc", varname = "RH", longname = "Relative Humidity (%)", overwrite = TRUE)

```



