---
title: "work"
output: pdf_document
date: "2026-01-21"
---

```{r}
rm(list = ls())
setwd("/cloud/project/")
# renv::activate()
library(terra)
library(ncdf4)
library(maps)
library(climetrics)
library(vars)
```

```{r}
# Let's focus on Eastern Canada
# Focusing on a region will reduce the time required for running the code
# domain <- c(0, 80, 43, 55) # Eastern Canada
domain <- c(0, 360, -90, 90) # undefined domain

# Fractional area burn
data <- terra::rast("data/burntFractionAll_GFED4S_128x64.nc")
data <- crop(x = data, y = domain)
# data <- subset(data, 12:287) # Subset Jan 2001 to Dec 2023
# data <- aggregate(x = data, fact=2, fun="mean") # More coarse spatial resolution
crs(data) <- "EPSG:4326" # assign a map projection (WGS84)
# evi <- data
mask <- mean(data) # create mask
mask <- mask - mask + 1 # make boolean mask
# rm(data)

# Precipitation (m)
data1 <- terra::rast("data/ERA5_pr_2001-2023.nc")
data1 <- crop(x = data1, y = domain)
data1 <- terra::resample(x = data1, y = mask) # resample to fire grid
crs(data1) <- "EPSG:4326" # assign a map projection (WGS84)
data <- data1 * mask # exclude gridcells that both data sets do not have in common
pr <- data1 * 1000 # convert unit from m to mm
rm(data1)

```

## Fractional area burned

```{r}



```

## Precipitation

```{r}

data <- pr

# Create a sequence of dates
start_date <- as.Date("2001-01-15")
end_date <- as.Date("2023-12-15")
dates <- seq(from = start_date, to = end_date, by = "month")

# Create raster time series
data.ts <- rts(data, dates)

# Calculate 12-month climatological means
data.12 <- apply.months(data.ts,'mean')

# Plot 12 months of data
my.col <- rev(map.pal("magma", n = 100))
plot(data.12, col = my.col)

```

```{r}

# Get the number of years
n <- length(dates)/12

# Create a time series where the 12-month climatological mean repeats for all years 
data.clim <- rep(data.12, n)

# Calculate anomalies
data.anom <- data - data.clim

# Have a look at the data
my.col <- rev(map.pal("magma", n = 100))
plot(subset(data.anom, 1:1), col = my.col)
map("world2", add = TRUE)

```

```{r}

# Define a function that removes a linear trend
detrend.fun <- function(x) {
  time <- 1:length(x)
  # If a grid cell contains NA, then set the result to NA
  if (is.na(mean(x))) {
    return(rep(NA, length(time)))
  } else {
    time <- 1:length(x)
    linear.model <- lm(x ~ time)
    detrended.series <- stats::residuals(linear.model)
    return(detrended.series)
  }
}

data.anom.detrend <- app(x = data.anom, fun = detrend.fun)
pr.anom.detrend <- data.anom.detrend

# Have a look at the data
my.col <- rev(map.pal("magma", n = 100))
plot(subset(data.anom.detrend, 1:1), col = my.col)
map("world2", add = TRUE)

```

```{r}

granger.fun <- function(x) {
  
    # If a grid cell contains NA, then set the result to NA
  if (is.na(mean(x))) {
    return(NA)
  } else {
    
  n <- length(x)
  # Get first (a) and second (b) variable
  a <- x[1:(n/2)]
  b <- x[(n/2+1):n]
  # Convert to time series
  a <- ts(a)
  b <- ts(b)
  tsDat <- ts.union(a, b)
  tsVAR <- vars::VAR(tsDat, p = 2)
  # Apply Granger causality test 
  p.value <- c(vars::causality(tsVAR, cause = "a")$Granger[3]$p.value)
  return(p.value)
  }
}

```

```{r}

granger.fun <- function(x) {
  
    # If a grid cell contains NA, then set the result to NA
  if (is.na(mean(x))) {
    return(NA)
  } else {
    
  n <- length(x)
  # Get first (a) and second (b) variable
  a <- x[1:(n/2)]
  b <- x[(n/2+1):n]
  # Convert to time series
  a <- ts(a)
  b <- ts(b)
  tsDat <- ts.union(a, b)
  tsVAR <- vars::VAR(tsDat, p = 2)
  # Apply Granger causality test 
  p.value <- c(vars::causality(tsVAR, cause = "a")$Granger[3]$p.value)
  return(p.value)
  }
}

```

```{r}

data <- pr

# Create a sequence of dates
start_date <- as.Date("2001-01-15")
end_date <- as.Date("2023-12-15")
dates <- seq(from = start_date, to = end_date, by = "month")

# Create raster time series
data.ts <- rts(data, dates)

# Calculate 12-month climatological means
data.12 <- apply.months(data.ts,'mean')

# Plot 12 months of data
my.col <- rev(map.pal("magma", n = 100))
plot(data.12, col = my.col)

```

```{r}

# Get the number of years
n <- length(dates)/12

# Create a time series where the 12-month climatological mean repeats for all years 
data.clim <- rep(data.12, n)

# Calculate anomalies
data.anom <- data - data.clim

# Have a look at the data
my.col <- rev(map.pal("magma", n = 100))
plot(subset(data.anom, 1:1), col = my.col)
map("world2", add = TRUE)

```

```{r}

# Define a function that removes a linear trend
detrend.fun <- function(x) {
  time <- 1:length(x)
  # If a grid cell contains NA, then set the result to NA
  if (is.na(mean(x))) {
    return(rep(NA, length(time)))
  } else {
    time <- 1:length(x)
    linear.model <- lm(x ~ time)
    detrended.series <- stats::residuals(linear.model)
    return(detrended.series)
  }
}

data.anom.detrend <- app(x = data.anom, fun = detrend.fun)
pr.anom.detrend <- data.anom.detrend

# Have a look at the data
my.col <- rev(map.pal("magma", n = 100))
plot(subset(data.anom.detrend, 1:1), col = my.col)
map("world2", add = TRUE)

```

```{r}

granger.fun <- function(x) {
  
    # If a grid cell contains NA, then set the result to NA
  if (is.na(mean(x))) {
    return(NA)
  } else {
    
  n <- length(x)
  # Get first (a) and second (b) variable
  a <- x[1:(n/2)]
  b <- x[(n/2+1):n]
  # Convert to time series
  a <- ts(a)
  b <- ts(b)
  tsDat <- ts.union(a, b)
  tsVAR <- vars::VAR(tsDat, p = 2)
  # Apply Granger causality test 
  p.value <- c(vars::causality(tsVAR, cause = "a")$Granger[3]$p.value)
  return(p.value)
  }
}

```

```{r}

granger.fun <- function(x) {
  
    # If a grid cell contains NA, then set the result to NA
  if (is.na(mean(x))) {
    return(NA)
  } else {
    
  n <- length(x)
  # Get first (a) and second (b) variable
  a <- x[1:(n/2)]
  b <- x[(n/2+1):n]
  # Convert to time series
  a <- ts(a)
  b <- ts(b)
  tsDat <- ts.union(a, b)
  tsVAR <- vars::VAR(tsDat, p = 2)
  # Apply Granger causality test 
  p.value <- c(vars::causality(tsVAR, cause = "a")$Granger[3]$p.value)
  return(p.value)
  }
}

```


```{r}

# Stack your raster objects, where the first part is the cause and the second the response
data <- c(pr.anom.detrend, evi.anom.detrend)

# Assess Granger causality
p.value <- app(x = data, fun = granger.fun)

# Create a boolean map where all locations with p-values < 0.01 equal 1 and all remaining gridcells equal zero
p.value[p.value >= 0.05] <- 0
p.value[p.value > 0] <- 1

p.value.pr <- p.value

plot(p.value, col = c("white", "orange"), main = "Precipitation Granger-causes area burned Anomalies")
map("world2", add = TRUE, interior = FALSE)

```

```{r}
# Near-surface temperature (K)
data <- terra::rast("data/ERA5_tas_2001-2023.nc")
data <- crop(x = data, y = domain)
data <- aggregate(x = data, fact=2, fun="mean") # More coarse spatial resolution
crs(data) <- "EPSG:4326" # assign a map projection (WGS84)
data <- data * mask # exclude gridcells that both data sets do not have in common
tas <- data
rm(data)

# Fractional Area Burnt
#data <- terra::rast("data/burn/burntFractionAll_GFED4S_128x64.nc + burntFractionAll_GFED4S_360x180.nc")
#data <- crop(x = data, y = domain)

# Wind Speed

# Relative Humidity

# Soil moisture
```

New code chunk

```{r}
a <- 1
```